# Generated by Django 5.2 on 2025-04-10 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('policynum', models.CharField(db_collation='utf8mb3_general_ci', db_column='PolicyNum', max_length=255, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_collation='utf8mb3_general_ci', db_column='Provider', max_length=255)),
                ('generaldeductible', models.IntegerField(blank=True, db_column='GeneralDeductible', null=True)),
                ('ooplimit', models.IntegerField(blank=True, db_column='OOPLimit', null=True)),
                ('primaryfee', models.DecimalField(blank=True, db_column='PrimaryFee', decimal_places=2, max_digits=5, null=True)),
                ('primaryfeetype', models.CharField(blank=True, db_column='PrimaryFeeType', max_length=25, null=True)),
                ('specialistfee', models.DecimalField(blank=True, db_column='SpecialistFee', decimal_places=2, max_digits=5, null=True)),
                ('specialistfeetype', models.CharField(blank=True, db_column='SpecialistFeeType', max_length=25, null=True)),
                ('otherfee', models.DecimalField(blank=True, db_column='OtherFee', decimal_places=2, max_digits=5, null=True)),
                ('otherfeetype', models.CharField(blank=True, db_column='OtherFeeType', max_length=25, null=True)),
                ('preventivefee', models.DecimalField(blank=True, db_column='PreventiveFee', decimal_places=2, max_digits=5, null=True)),
                ('preventivefeetype', models.CharField(blank=True, db_column='PreventiveFeeType', max_length=25, null=True)),
                ('diagnosticfee', models.DecimalField(blank=True, db_column='DiagnosticFee', decimal_places=2, max_digits=5, null=True)),
                ('diagnosticfeetype', models.CharField(blank=True, db_column='DiagnosticFeeType', max_length=25, null=True)),
                ('imagingfee', models.DecimalField(blank=True, db_column='ImagingFee', decimal_places=2, max_digits=5, null=True)),
                ('imagingfeetype', models.CharField(blank=True, db_column='ImagingFeeType', max_length=25, null=True)),
                ('genericfee', models.DecimalField(blank=True, db_column='GenericFee', decimal_places=2, max_digits=5, null=True)),
                ('genericfeetype', models.CharField(blank=True, db_column='GenericFeeType', max_length=25, null=True)),
                ('prefbrandfee', models.DecimalField(blank=True, db_column='PrefBrandFee', decimal_places=2, max_digits=5, null=True)),
                ('prefbrandfeetype', models.CharField(blank=True, db_column='PrefBrandFeeType', max_length=25, null=True)),
                ('npbrandfee', models.DecimalField(blank=True, db_column='NPBrandFee', decimal_places=2, max_digits=5, null=True)),
                ('npbrandfeetype', models.CharField(blank=True, db_column='NPBrandFeeType', max_length=25, null=True)),
                ('specialtyfee', models.DecimalField(blank=True, db_column='SpecialtyFee', decimal_places=2, max_digits=5, null=True)),
                ('specialtyfeetype', models.CharField(blank=True, db_column='SpecialtyFeeType', max_length=25, null=True)),
                ('facilityfee', models.DecimalField(blank=True, db_column='FacilityFee', decimal_places=2, max_digits=5, null=True)),
                ('facilityfeetype', models.CharField(blank=True, db_column='FacilityFeeType', max_length=25, null=True)),
                ('physicianfee', models.DecimalField(blank=True, db_column='PhysicianFee', decimal_places=2, max_digits=5, null=True)),
                ('physicianfeetype', models.CharField(blank=True, db_column='PhysicianFeeType', max_length=25, null=True)),
                ('erfee', models.DecimalField(blank=True, db_column='ERFee', decimal_places=2, max_digits=5, null=True)),
                ('erfeetype', models.CharField(blank=True, db_column='ERFeeType', max_length=25, null=True)),
                ('transportfee', models.DecimalField(blank=True, db_column='TransportFee', decimal_places=2, max_digits=5, null=True)),
                ('transportfeetype', models.CharField(blank=True, db_column='TransportFeeType', max_length=25, null=True)),
                ('ucfee', models.DecimalField(blank=True, db_column='UCFee', decimal_places=2, max_digits=5, null=True)),
                ('ucfeetype', models.CharField(blank=True, db_column='UCFeeType', max_length=25, null=True)),
                ('mhoutpatientfee', models.DecimalField(blank=True, db_column='MHOutpatientFee', decimal_places=2, max_digits=5, null=True)),
                ('mhoutpatientfeetype', models.CharField(blank=True, db_column='MHOutpatientFeeType', max_length=25, null=True)),
                ('mhinpatientfee', models.DecimalField(blank=True, db_column='MHInpatientFee', decimal_places=2, max_digits=5, null=True)),
                ('mhinpatientfeetype', models.CharField(blank=True, db_column='MHInpatientFeeType', max_length=25, null=True)),
                ('suoutpatientfee', models.DecimalField(blank=True, db_column='SUOutpatientFee', decimal_places=2, max_digits=5, null=True)),
                ('suoutpatientfeetype', models.CharField(blank=True, db_column='SUOutpatientFeeType', max_length=25, null=True)),
                ('suinpatientfee', models.DecimalField(blank=True, db_column='SUInpatientFee', decimal_places=2, max_digits=5, null=True)),
                ('suinpatientfeetype', models.CharField(blank=True, db_column='SUInpatientFeeType', max_length=25, null=True)),
                ('prenatalfee', models.DecimalField(blank=True, db_column='PrenatalFee', decimal_places=2, max_digits=5, null=True)),
                ('prenatalfeetype', models.CharField(blank=True, db_column='PrenatalFeeType', max_length=25, null=True)),
                ('deliveryfee', models.DecimalField(blank=True, db_column='DeliveryFee', decimal_places=2, max_digits=5, null=True)),
                ('deliveryfeetype', models.CharField(blank=True, db_column='DeliveryFeeType', max_length=25, null=True)),
                ('homecarefee', models.DecimalField(blank=True, db_column='HomeCareFee', decimal_places=2, max_digits=5, null=True)),
                ('homecarefeetype', models.CharField(blank=True, db_column='HomeCareFeeType', max_length=25, null=True)),
                ('rehabfee', models.DecimalField(blank=True, db_column='RehabFee', decimal_places=2, max_digits=5, null=True)),
                ('rehabfeetype', models.CharField(blank=True, db_column='RehabFeeType', max_length=25, null=True)),
                ('habilitationfee', models.DecimalField(blank=True, db_column='HabilitationFee', decimal_places=2, max_digits=5, null=True)),
                ('habilitationfeetype', models.CharField(blank=True, db_column='HabilitationFeeType', max_length=25, null=True)),
                ('skilledfee', models.DecimalField(blank=True, db_column='SkilledFee', decimal_places=2, max_digits=5, null=True)),
                ('skilledfeetype', models.CharField(blank=True, db_column='SkilledFeeType', max_length=25, null=True)),
                ('equipmentfee', models.DecimalField(blank=True, db_column='EquipmentFee', decimal_places=2, max_digits=5, null=True)),
                ('equipmentfeetype', models.CharField(blank=True, db_column='EquipmentFeeType', max_length=25, null=True)),
                ('hospicefee', models.DecimalField(blank=True, db_column='HospiceFee', decimal_places=2, max_digits=5, null=True)),
                ('hospicefeetype', models.CharField(blank=True, db_column='HospiceFeeType', max_length=25, null=True)),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'insurancepolicy',
            },
        ),
    ]
